apiVersion: apps/v1
kind: Deployment
metadata:
  name: oyjoh
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oyjoh
  template:
    metadata:
      labels:
        app: oyjoh
    spec:
      containers:
        - name: application
          image: registry.digitalocean.com/olsen/oyjoh
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
