apiVersion: apps/v1
kind: Deployment
metadata:
  name: oyvind-j-deployment
  namespace: apps
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: registry.digitalocean.com/olsen/oyvind-j
          image: registry.digitalocean.com/olsen/oyvind-j
          ports:
            - containerPort: 80
